# Generated by Django 4.2.28 on 2026-02-06 10:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import poker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='participant_name_help_text', max_length=255, verbose_name='participant_name_verbose')),
                ('authentication_key', models.CharField(default=poker.models.generate_auth_key, help_text='participant_authentication_key_help_text', max_length=255, unique=True, verbose_name='participant_authentication_key_verbose')),
                ('is_active', models.BooleanField(default=True, help_text='participant_is_active_help_text', verbose_name='participant_is_active_verbose')),
            ],
            options={
                'verbose_name': 'participant_verbose',
                'verbose_name_plural': 'participant_verbose_plural',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='room_name_help_text', max_length=255, verbose_name='room_name_verbose')),
                ('room_code', models.CharField(default=poker.models.generate_room_code, help_text='room_room_code_help_text', max_length=6, unique=True, verbose_name='room_room_code_verbose')),
                ('room_password', models.CharField(blank=True, help_text='room_room_password_help_text', max_length=255, null=True, verbose_name='room_room_password_verbose')),
                ('revealed', models.BooleanField(default=False, help_text='room_revealed_help_text', verbose_name='room_revealed_verbose')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='room_created_at_help_text', verbose_name='room_created_at_verbose')),
                ('is_active', models.BooleanField(default=True, help_text='room_is_active_help_text', verbose_name='room_is_active_verbose')),
            ],
            options={
                'verbose_name': 'room_verbose',
                'verbose_name_plural': 'room_verbose_plural',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='task_title_help_text', max_length=500, verbose_name='task_title_verbose')),
                ('description', models.TextField(blank=True, help_text='task_description_help_text', null=True, verbose_name='task_description_verbose')),
                ('sp', models.DecimalField(blank=True, decimal_places=1, help_text='task_sp_help_text', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='task_sp_verbose')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='task_metrics_help_text', verbose_name='task_metrics_verbose')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('voting', 'Oylama Devam Ediyor'), ('estimated', 'Tahmin Edildi'), ('completed', 'Tamamlandı')], default='pending', help_text='task_status_help_text', max_length=20, verbose_name='task_status_verbose')),
                ('is_active', models.BooleanField(default=True, help_text='task_is_active_help_text', verbose_name='task_is_active_verbose')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='task_created_at_help_text', verbose_name='task_created_at_verbose')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='task_updated_at_help_text', verbose_name='task_updated_at_verbose')),
                ('room', models.ForeignKey(help_text='task_room_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='poker.room', verbose_name='task_room_verbose')),
            ],
            options={
                'verbose_name': 'task_verbose',
                'verbose_name_plural': 'task_verbose_plural',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vote', models.CharField(help_text='task_vote_vote_help_text', max_length=10, verbose_name='task_vote_vote_verbose')),
                ('voted_at', models.DateTimeField(auto_now=True, help_text='task_vote_voted_at_help_text', verbose_name='task_vote_voted_at_verbose')),
                ('participant', models.ForeignKey(help_text='task_vote_participant_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.participant', verbose_name='task_vote_participant_verbose')),
                ('task', models.ForeignKey(help_text='task_vote_task_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.task', verbose_name='task_vote_task_verbose')),
            ],
            options={
                'verbose_name': 'task_vote_verbose',
                'verbose_name_plural': 'task_vote_verbose_plural',
                'ordering': ['voted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_code'], name='poker_room_room_co_17e691_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_active', '-created_at'], name='poker_room_is_acti_ce1c93_idx'),
        ),
        migrations.AddField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(help_text='participant_room_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='poker.room', verbose_name='participant_room_verbose'),
        ),
        migrations.AddIndex(
            model_name='taskvote',
            index=models.Index(fields=['task', 'participant'], name='poker_taskv_task_id_de8386_idx'),
        ),
        migrations.AddIndex(
            model_name='taskvote',
            index=models.Index(fields=['task', 'voted_at'], name='poker_taskv_task_id_11406b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskvote',
            unique_together={('task', 'participant')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['room', 'is_active'], name='poker_task_room_id_d3d48e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['room', 'status'], name='poker_task_room_id_4a3534_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['authentication_key'], name='poker_parti_authent_4a8112_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['room', 'is_active'], name='poker_parti_room_id_c333ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('room', 'name')},
        ),
    ]
