# Generated by Django 4.2.28 on 2026-02-08 17:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import poker.models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'model_participant_verbose', 'verbose_name_plural': 'model_participant_verbose_plural'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at'], 'verbose_name': 'model_room_verbose', 'verbose_name_plural': 'model_room_verbose_plural'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'model_task_verbose', 'verbose_name_plural': 'model_task_verbose_plural'},
        ),
        migrations.AlterModelOptions(
            name='taskvote',
            options={'ordering': ['voted_at'], 'verbose_name': 'model_task_vote_verbose', 'verbose_name_plural': 'model_task_vote_verbose_plural'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='authentication_key',
            field=models.CharField(default=poker.models.generate_auth_key, help_text='model_participant_authentication_key_help_text', max_length=255, unique=True, verbose_name='model_participant_authentication_key_verbose'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='model_participant_is_active_help_text', verbose_name='model_participant_is_active_verbose'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(help_text='model_participant_name_help_text', max_length=255, verbose_name='model_participant_name_verbose'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='room',
            field=models.ForeignKey(help_text='model_participant_room_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='poker.room', verbose_name='model_participant_room_verbose'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='model_room_created_at_help_text', verbose_name='model_room_created_at_verbose'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, help_text='model_room_is_active_help_text', verbose_name='model_room_is_active_verbose'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(help_text='model_room_name_help_text', max_length=255, verbose_name='model_room_name_verbose'),
        ),
        migrations.AlterField(
            model_name='room',
            name='revealed',
            field=models.BooleanField(default=False, help_text='model_room_revealed_help_text', verbose_name='model_room_revealed_verbose'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(default=poker.models.generate_room_code, help_text='model_room_room_code_help_text', max_length=6, unique=True, verbose_name='model_room_room_code_verbose'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_password',
            field=models.CharField(blank=True, help_text='model_room_room_password_help_text', max_length=255, null=True, verbose_name='model_room_room_password_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='model_task_created_at_help_text', verbose_name='model_task_created_at_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='model_task_description_help_text', null=True, verbose_name='model_task_description_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, help_text='model_task_is_active_help_text', verbose_name='model_task_is_active_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='model_task_metrics_help_text', verbose_name='model_task_metrics_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ForeignKey(help_text='model_task_room_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='poker.room', verbose_name='model_task_room_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='sp',
            field=models.IntegerField(blank=True, help_text='model_task_sp_help_text', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='model_task_sp_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Beklemede'), ('voting', 'Oylama Devam Ediyor'), ('estimated', 'Tahmin Edildi'), ('completed', 'Tamamlandı')], default='pending', help_text='model_task_status_help_text', max_length=20, verbose_name='model_task_status_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='model_task_title_help_text', max_length=500, verbose_name='model_task_title_verbose'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='model_task_updated_at_help_text', verbose_name='model_task_updated_at_verbose'),
        ),
        migrations.AlterField(
            model_name='taskvote',
            name='participant',
            field=models.ForeignKey(help_text='model_task_vote_participant_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.participant', verbose_name='model_task_vote_participant_verbose'),
        ),
        migrations.AlterField(
            model_name='taskvote',
            name='task',
            field=models.ForeignKey(help_text='model_task_vote_task_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.task', verbose_name='model_task_vote_task_verbose'),
        ),
        migrations.AlterField(
            model_name='taskvote',
            name='vote',
            field=models.CharField(help_text='model_task_vote_vote_help_text', max_length=10, verbose_name='model_task_vote_vote_verbose'),
        ),
        migrations.AlterField(
            model_name='taskvote',
            name='voted_at',
            field=models.DateTimeField(auto_now=True, help_text='model_task_vote_voted_at_help_text', verbose_name='model_task_vote_voted_at_verbose'),
        ),
    ]
