# Generated by Django 4.2.28 on 2026-02-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_alter_participant_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'model_task_status_pending'), ('voting', 'model_task_status_voting'), ('estimated', 'model_task_status_estimated'), ('completed', 'model_task_status_completed')], default='pending', help_text='model_task_status_help_text', max_length=20, verbose_name='model_task_status_verbose'),
        ),
    ]
