# Generated by Django 4.2.28 on 2026-02-10 14:57

from django.db import migrations, models
import poker.models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('room', 'name')},
        ),
        migrations.AlterField(
            model_name='participant',
            name='authentication_key',
            field=models.CharField(default=poker.models.generate_auth_key, help_text='model_participant_authentication_key_help_text', max_length=255, verbose_name='model_participant_authentication_key_verbose'),
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('room', 'authentication_key'), ('room', 'name')},
        ),
    ]
