# Generated by Django 4.2.28 on 2026-02-14 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0004_alter_participant_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='model_sprint_name_help_text', max_length=500, verbose_name='model_sprint_name_verbose')),
                ('is_active', models.BooleanField(default=True, help_text='model_sprint_is_active_help_text', verbose_name='model_sprint_is_active_verbose')),
            ],
            options={
                'verbose_name': 'model_sprint_verbose',
                'verbose_name_plural': 'model_sprint_verbose_plural',
            },
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='poker_parti_authent_4a8112_idx',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(blank=True, help_text='model_participant_user_help_text', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_entries', to=settings.AUTH_USER_MODEL, verbose_name='model_participant_user_verbose'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='taskvote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_user'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='room',
            field=models.ForeignKey(help_text='model_sprint_room_help_text', on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='poker.room', verbose_name='model_sprint_room_verbose'),
        ),
        migrations.AddField(
            model_name='sprint',
            name='tasks',
            field=models.ManyToManyField(blank=True, help_text='model_sprint_tasks_help_text', related_name='sprints_in', to='poker.task', verbose_name='model_sprint_tasks_verbose'),
        ),
        migrations.RemoveField(
            model_name='participant',
            name='authentication_key',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='name',
        ),
        migrations.AddIndex(
            model_name='sprint',
            index=models.Index(fields=['room', 'is_active'], name='poker_sprin_room_id_faf2af_idx'),
        ),
        migrations.AddConstraint(
            model_name='sprint',
            constraint=models.UniqueConstraint(fields=('room', 'name'), name='unique_room_sprint'),
        ),
    ]
