# Generated by Django 4.2.28 on 2026-02-14 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_sprint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sprint',
            options={'ordering': ['-created_at'], 'verbose_name': 'model_sprint_verbose', 'verbose_name_plural': 'model_sprint_verbose_plural'},
        ),
        migrations.AddField(
            model_name='sprint',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='model_sprint_created_at_help_text', verbose_name='model_sprint_created_at_verbose'),
        ),
    ]
