# Generated by Django 4.2.28 on 2026-02-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_alter_sprint_options_sprint_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='revealed',
        ),
        migrations.AddField(
            model_name='sprint',
            name='revealed',
            field=models.BooleanField(default=False, help_text='model_sprint_revealed_help_text', verbose_name='model_sprint_revealed_verbose'),
        ),
    ]
